def create_yo_glyph_9_bmp() -> bytes:
    """
    Dynamically generates the raw bytes of a 24-bit uncompressed BMP image (10x10 pixels).
    Draws the top (bit_3) and right (bit_0) outer edges in BLACK (0,0,0) to represent the value 9.
    The background is filled with WHITE (255, 255, 255).
    """
    width, height = 10, 10
    
    # In 24-bit BMP, row size must be padded to a multiple of 4 bytes.
    # 10 pixels * 3 bytes (BGR) = 30 bytes. The closest multiple of 4 is 32 bytes.
    row_size = 32  
    pixel_data_size = row_size * height
    file_size = 54 + pixel_data_size # 54 bytes for the standard BMP header structure

    # 1. Generate the BMP File Header (14 bytes)
    header = bytearray(14)
    header[0:2] = b'BM'                                    # Signature / Magic Number
    header[2:6] = file_size.to_bytes(4, 'little')          # Total size of the BMP file
    header[10:14] = (54).to_bytes(4, 'little')            # Offset where the pixel data begins

    # 2. Generate the DIB Header (BITMAPINFOHEADER - 40 bytes)
    dib = bytearray(40)
    dib[0:4] = (40).to_bytes(4, 'little')                 # Size of this DIB header
    dib[4:8] = width.to_bytes(4, 'little')                # Image width in pixels
    dib[8:12] = height.to_bytes(4, 'little')              # Image height in pixels
    dib[12:14] = (1).to_bytes(2, 'little')                # Number of color planes (must be 1)
    dib[14:16] = (24).to_bytes(2, 'little')               # Bits per pixel (24-bit true color)
    dib[20:24] = pixel_data_size.to_bytes(4, 'little')    # Size of the raw pixel array

    # 3. Initialize the canvas with a solid white background (255, 255, 255)
    pixels = bytearray(pixel_data_size)
    for y in range(height):
        for x in range(width):
            idx = (y * row_size) + (x * 3)
            pixels[idx:idx+3] = b'\xff\xff\xff'

    # 4. Render the YOalphabet geometry for Decimal 9 (Binary 1001)
    # Bit 3 (Top Edge): Y = 9 (the highest row index) -> Fill with black pixels
    for x in range(width):
        idx = (9 * row_size) + (x * 3)
        pixels[idx:idx+3] = b'\x00\x00\x00'

    # Bit 0 (Right Edge): X = 9 (the rightmost column index) -> Fill with black pixels
    for y in range(height):
        idx = (y * row_size) + (9 * 3)
        pixels[idx:idx+3] = b'\x00\x00\x00'

    return bytes(header + dib + pixels)


def decode_yo_glyph_from_bytes(bmp_bytes: bytes) -> dict:
    """
    Parses the raw structure of a 24-bit BMP file and extracts the states
    of spatial bit registers at deterministic coordinates.
    """
    # Extract structural metadata directly from fixed byte positions
    pixel_offset = int.from_bytes(bmp_bytes[10:14], byteorder='little')
    width = int.from_bytes(bmp_bytes[18:22], byteorder='little')
    height = int.from_bytes(bmp_bytes[22:26], byteorder='little')
    
    # Calculate row size including the 4-byte padding restriction
    row_size = ((width * 3 + 3) // 4) * 4
    
    def is_pixel_black(x: int, y: int) -> int:
        """Checks pixel color at target coordinates. Returns 1 if active (black), 0 if vacant."""
        idx = pixel_offset + (y * row_size) + (x * 3)
        b, g, r = bmp_bytes[idx], bmp_bytes[idx+1], bmp_bytes[idx+2]
        return 1 if (b == 0 and g == 0 and r == 0) else 0

    # Scan the center pixels of the four outer geometric registers (10x10 matrix, indices 0-9)
    bit_0 = is_pixel_black(9, 5)  # Right vertical edge
    bit_1 = is_pixel_black(5, 0)  # Bottom horizontal edge
    bit_2 = is_pixel_black(0, 5)  # Left vertical edge
    bit_3 = is_pixel_black(5, 9)  # Top horizontal edge

    # Geometric Activation Function: D = SUM (b_n * 2^n)
    decimal_value = (bit_0 * 1) + (bit_1 * 2) + (bit_2 * 4) + (bit_3 * 8)
    binary_string = f"{bit_3}{bit_2}{bit_1}{bit_0}"
    
    return {
        "binary": binary_string,
        "decimal": decimal_value,
        "dimensions": f"{width}x{height}"
    }


if __name__ == "__main__":
    print("--- YOalphabet Zero-Dependency Real-Pixel Decoder ---")
    
    try:
        # Programmatically synthesize the reference BMP file for test verification
        raw_bmp_bytes = create_yo_glyph_9_bmp()
        
        # Parse the generated byte stream using the isomorphic geometry decoder
        result = decode_yo_glyph_from_bytes(raw_bmp_bytes)
        
        print(f"Image Dimensions: {result['dimensions']}")
        print(f"Decoded Binary State: {result['binary']}")
        print(f"Decoded Decimal Value: {result['decimal']}")
        print("Success: Decoded via direct byte tracking of spatial registers!")
        
        # Write the file to disk to provide a downloadable visual artifact
        filename = "yo_glyph_9.bmp"
        with open(filename, "wb") as f:
            f.write(raw_bmp_bytes)
        print(f"\n[FILE GENERATED]: Real image saved as '{filename}'.")
        print("You can download it now. The alignment is mathematically perfect.")
        
    except Exception as e:
        print(f"Decoder Critical Error: {e}")
        